version: '3.9'

services:
  app:
    build: .
    container_name: moondancer_app
    ports:
      - "8080:8080"   # Flask Backend
      - "8501:8501"   # Streamlit Frontend
    environment:
      - FLASK_ENV=production
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - database

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  database:
    image: mysql
    environment:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_HOST:
      MYSQL_PORT: 23140
      MYSQL_DB: "defaultdb"
    ports:
      - "3307:3307"
