version: '3.9'

services:
  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
  app:
    build: .
    container_name: moondancer_app
    ports:
      - "5000:5000"   # Flask Backend
      - "8501:8501"   # Streamlit Frontend
    environment:
      - FLASK_ENV=production
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
